# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94d8f4eae7f966787307cbfe97decfa58c7cd5b64a2c3720b40635a3efe9e823b0ed70dea3e99c9eb5bf27783afd28515b488a590c78e4eca0bf1e394e8bce75

test:
  secret_key_base: a22d58674a92e54d545aab816df493d07bda25b14464fae4506ba483d51de23aa836c84921948d2c0ebf714b1d7d52b262049bef7e1d1106693853cf9ac6462c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
